#:schema ../../capabilities.schema.json
version = 1
imports = [
  "../../zarr-extensions/codecs/n5_default/capabilities.toml",
]

[capabilities."zarr/v3/codec/n5_default/decode"]
support = true

[capabilities."zarr/v3/codec/n5_default/decode_partial"]
support = false

[capabilities."zarr/v3/codec/n5_default/encode"]
support = false

[capabilities."zarr/v3/codec/n5_default/encode_partial"]
support = false
