#:schema https://raw.githubusercontent.com/clbarnes/capability-manifest/refs/heads/main/capabilities.schema.json
version = 1
imports = [
  "https://raw.githubusercontent.com/clbarnes/capability-manifest/refs/heads/main/examples/zarr-extensions/codecs/n5_default/capabilities.toml",
]

[capabilities."zarr/v3/codec/n5_default/decode"]
support = true

[capabilities."zarr/v3/codec/n5_default/decode_partial"]
support = false

[capabilities."zarr/v3/codec/n5_default/encode"]
support = false

[capabilities."zarr/v3/codec/n5_default/encode_partial"]
support = false
